### ISSUE TITLE
Concurrent calls using the same context with headers could lead to a panic

### ISSUE THREAD

**Issue by prashantv** [uber/tchannel-go#505]
The thrift client calls `InjectOutboundSpan` with the headers passed in to the context,
https://github.com/uber/tchannel-go/blob/dev/thrift/client.go#L69

This method will modify the passed in map (if it's not nil):
https://github.com/uber/tchannel-go/blob/dev/tracing.go#L178

If there's concurrent calls using the same context with the same map, they will both try to modify the map (causing a data race) which since go1.7 may also trigger the following panic:
```
fatal error: concurrent map writes
```

@yurishkuro

**Comment by yurishkuro** [comment]
If the `headers` map passed to `InjectOutboundSpan` can be a shared singleton map, then we always need to make a copy. I would suggest the following sequence
  * create a new map, use it to inject tracing headers
  * if the input `headers` was nil, return the new map with headers
  * otherwise copy values from `headers` into the new map and return it
