### ISSUE TITLE
Update Thrift to v0.13.0

### ISSUE THREAD

**Issue by nilebox** [uber/tchannel-go#781]
`tchannel-go` is using an outdated Thrift dependency, which causes dependency conflict issues in the projects depending on it.

Examples:
- https://github.com/jaegertracing/jaeger/issues/1972
- OpenTelemetry Collector:

The [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector) repo includes Jaeger and Prometheus receivers, so it has Go Module dependencies on both - https://github.com/jaegertracing/jaeger and https://github.com/prometheus/prometheus.

When I update the Prometheus dependency to the latest v2.19.0 release, it brings the [Thrift v0.13.0 dependency](https://github.com/prometheus/prometheus/blob/v2.19.0/go.sum#L90) along, which breaks the Jaeger receiver compilation and complains about `tchannel-go` method mismatch, since it's using older Thrift version.

Seems like there were breaking changes in Thrift API between v0.9.3 and v0.13.0, and the only way to fix this dependency hell is to update `uber/tchannel-go` to use `apache/thrift` v0.13.0, or remove a dependency on `tchannel-go` from Jaeger.

**Comment by nilebox** [comment]
Note that `tchannel-go` uses a custom `thrift-gen` binary attached to a tag https://github.com/uber/tchannel-go/releases/tag/thrift-v1.0.0-dev, e.g. https://github.com/uber/tchannel-go/releases/download/thrift-v1.0.0-dev/thrift-1-linux-x86_64.tar.gz for Linux platform.

**Comment by prashantv** [comment]
Updating to Thrift > 0.11 has a breaking API change (added `context.Context` to the Thrift interfaces), and updating our library to use the newer version would similarly be a breaking API change for all the clients using TChannel.

We follow semver, and cannot cut a 1.x release that updates to the latest Thrift APIs, which is why we are pinned to to <= 0.11. Cutting a 2.x release is not something we are planning on.

@ys Can you use YARPC's TChannel + Thrift integration in Jaeger, which should remove the dependency on Apache Thrift? This will avoid any dependency constraints required for tchannel-go/thrift from affecting clients using OpenTelemetry.

**Comment by nilebox** [comment]
@prashantv the issue blocking OpenTelemetry collector has been fixed on the Jaeger side in #2311.
Feel free to close this issue as "won't fix" if you don't plan to update Thrift dependency in `tchannel-go`.

**Comment by prashantv** [comment]
Thanks for the update. Since we won't be able to update without a 2.x release, and that will require significant work for clients, closing this as Wont Fix.
